version: "3.9"

networks:
  proxy:
    external: true
  backend:
    external: false

services:
  dash:
    build: 
      context: ./
    container_name : "${COMPOSE_PROJECT_NAME}_dashboard"
    hostname: "${COMPOSE_PROJECT_NAME}_dashboard"
    ports:
      - "5000:8090"
    networks:
      - proxy
      - backend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashkami.rule=Host(`dash.kamico.com.br`)
      - traefik.http.routers.dashkami.tls.certresolver=myresolver
      - traefik.port=80