# -*- coding: utf-8 -*-

from datetime import datetime, timedelta

import numpy as np

MONTHS_PTBR = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro',
}
MONTHS_PTBR_ABBR = {
    1: 'JAN',
    2: 'FEV',
    3: 'MAR',
    4: 'ABR',
    5: 'MAI',
    6: 'JUN',
    7: 'JUL',
    8: 'AGO',
    9: 'SET',
    10: 'OUT',
    11: 'NOV',
    12: 'DEZ',
}
WEEKDAYS_PTBR_ABBR = {
    0: 'SEG',
    1: 'TER',
    2: 'QUA',
    3: 'QUI',
    4: 'SEX',
    5: 'SAB',
    6: 'DOM',
}
TAGS = ['_liquido', '_bruto', '_desconto', '_bonificado', '_enxoval']
STARTING_YEAR = 2022
CURRENT_MONTH = datetime.now().month
CURRENT_YEAR = datetime.now().year
CURRENT_DAY = datetime.now().day
END_WEEK = datetime.now() - timedelta(days=datetime.today().weekday())
START_WEEK = END_WEEK - timedelta(days=7)
CURRENT_WEEKDAY = datetime.today().weekday()
WEEK_YEAR_NUMBER = datetime.now().strftime('%V')
CURRENT_WEEK_FOLDER = f'Semana-{WEEK_YEAR_NUMBER} ({START_WEEK.day}-{START_WEEK.month} a {END_WEEK.day}-{END_WEEK.month})'
CURRENT_DAY_FOLDER = f'{CURRENT_DAY}-{WEEKDAYS_PTBR_ABBR[CURRENT_WEEKDAY]}'
COMERCIAL_WEEK = [0, 1, 2, 3, 4]
COLUMNS_NAMES_HEAD = [
    'cod_colaborador',
    'nome_colaborador',
    'cod_cliente',
    'nome_cliente',
    'razao_social',
    'ramo_atividade',
    'data_cadastro',
    'bairro',
    'cidade',
    'uf',
    'endereco',
    'numero',
    'cep',
    'dias_atraso',
    'valor_devido',
    'dt_primeira_compra',
    'dt_ultima_compra',
    'cod_marca',
    'desc_marca',
    'STATUS',
]
SALE_NOPS = [
    '6.102',
    '6.404',
    'BLACKFRIDAY',
    'VENDA',
    'VENDA_S_ESTOQUE',
    'WORKSHOP',
]
SUBSIDIZED_NOPS = [
    'BONIFICADO',
    'BONIFICADO_F',
    'BONI_COMPRA',
    'PROMOCAO',
    'PROMO_BLACK',
    'CAMPANHA',
]
TROUSSEAU_NOPS = ['ENXOVAL']
TRANS_COLS = {
    'company': 'Empresa',
    'branch': 'Canal de Vendas',
    'uf': 'Estado',
    'salesperson': 'Vendedores',
}
COMPANIES = {
    1: 'KAMI CO',
    2: 'NEW HAUSS',
    3: 'MOVEMENT SP',
    4: 'ENERGY',
    5: 'HAIRPRO',
    6: 'SOUTH',
    9: 'MMS',
    10: '3MKO MATRIZ',
    11: '3MKO FILIAL SP',
    12: '3MKO FILIAL ES',
    13: 'MOVEMENT RJ',
    14: '3MKO FILIAL PR',
    15: 'MOVEMENT MT',
    16: 'MOVEMENT RS',
}
TEMPLATE_COLS = [
    'ano',
    'mes',
    'cod_cliente',
    'nome_cliente',
    'ramo_atividade',
    'bairro',
    'cidade',
    'uf',
    'cod_colaborador',
    'nome_colaborador',
    'cod_situacao',
    'desc_situacao',
    'cod_grupo_produto',
    'desc_grupo_produto',
    'cod_grupo_pai',
    'desc_grupo_pai',
    'cod_marca',
    'desc_marca',
    'empresa_nota_fiscal',
]
FILTER_COLS = [
    'Ano',
    'Mês',
    'Empresa',
    'Marca',
    'Vendedores',
    'Canal de Vendas',
    'Estado',
    'Situação',
]
CUSTOMER_DETAILS_NUM_COLS = {
    'cod_cliente': np.int64,
    'dias_atraso': np.int64,
    'valor_devido': np.float64,
    'ultimo_ano_ativo': np.int64,
}
CUSTOMER_DETAILS_DATETIME_COLS = [
    'data_cadastro',
    'dt_primeira_compra',
    'dt_ultima_compra',
]
DAILY_BILLINGS_NUM_COLS = {
    'ano': np.int64,
    'mes': np.int64,
    'empresa_pedido': np.int64,
    'empresa_nota_fiscal': np.int64,
    'cod_cliente': np.int64,
    'cod_colaborador': np.int64,
    'cod_pedido': np.int64,
    'cod_situacao': np.int64,
    'cod_grupo_produto': np.int64,
    'cod_grupo_pai': np.int64,
    'cod_marca': np.int64,
    'custo_total': np.float64,
    'custo_kami': np.float64,
    'qtd': np.int64,
    'preco_unit_original': np.float64,
    'preco_total_original': np.float64,
    'margem_bruta': np.float64,
    'preco_total': np.float64,
    'preco_desconto_rateado': np.float64,
    'vl_total_pedido': np.float64,
    'desconto_pedido': np.float64,
    'valor_nota': np.float64,
    'total_bruto': np.float64,
}
MONTHLY_BILLINGS_NUM_COLS = {
    'ano': np.int64,
    'mes': np.int64,
    'cod_empresa': np.int64,
    'cod_pedido': np.int64,
    'cod_cliente': np.int64,
    'situacao_pedido': np.int64,
    'cod_colaborador': np.int64,
    'qtd': np.int64,
    'custo_total': np.float64,
    'custo_kami': np.float64,
    'preco_unit_original': np.float64,
    'preco_total_original': np.float64,
    'margem_bruta': np.float64,
    'preco_total': np.float64,
    'preco_desconto_rateado': np.float64,
    'vl_total_pedido': np.float64,
    'desconto_pedido': np.float64,
    'valor_nota': np.float64,
    'situacao_entrega': np.int64,
    'empresa_pedido': np.int64,
    'empresa_nf': np.int64,
}
MONTHLY_BILLINGS_SCRIPT = 'SELECT * FROM vw_monthly_billings'
DAILY_BILLINGS_SCRIPT = f'SELECT * FROM vw_daily_billings AS vdb \
    WHERE vdb.ano >= {STARTING_YEAR}'
CUSTOMER_DETAILS_SCRIPT = f'SELECT * FROM vw_customer_details AS vcd WHERE vcd.ultimo_ano_ativo >= {STARTING_YEAR}'
BILLINGS_DATETIME_COLS = [
    'dt_implante_pedido',
    'dt_entrega_comprometida',
    'dt_faturamento',
]
ODERS_COLS_HEAD = [
    'ano',
    'mes',
    'empresa_pedido',
    'empresa_nota_fiscal',
    'cod_cliente',
    'cod_colaborador',
    'nome_colaborador',
    'cod_pedido',
    'nr_ped_compra_cli',
    'cod_situacao',
    'desc_situacao',
    'nop',
    'cfop',
    'cod_cond_pagto',
    'cod_forma_pagto',
    'forma_pgto',
    'tb_preco',
    'vl_total_pedido',
    'desconto_pedido',
    'valor_nota',
    'total_bruto',
    'dt_implante_pedido',
    'dt_entrega_comprometida',
    'dt_faturamento',
]
SALES_TEAMS = {
    6: 'Adriana David',
    385: 'Alexandre Nascimento',
    161: 'Adriana David',
    107: 'Carlos Benia',
    3337: 'Alexandre Nascimento',
    3387: 'Uso Próprio',
    13: 'Adriana David',
    14: 'Adriana David',
    15: 'Sávio Almeida',
    16: 'Uso Próprio',
    158: 'Rogerio Casado',
    85: 'Rogerio Casado',
    303: 'Amanda Bêtta',
    18: 'Carlos Gouveia',
    21: 'Carlos Benia',
    387: 'Maurício Rodrigues',
    22: 'Adriana David',
    358: 'Maisa Ekermann',
    23: 'Herbert Marcondes',
    222: 'Adriana David',
    381: 'Adriana David',
    24: 'Sávio Almeida',
    17: 'Adriana David',
    3342: 'Alexandre Nascimento',
    27: 'Adriana David',
    253: 'Renato Mimoto',
    31: 'Sávio Almeida',
    364: 'Amanda Bêtta',
    215: 'Alexandre Nascimento',
    383: 'Maisa Ekermann',
    3425: 'Sávio Almeida',
    35: 'Alexandre Nascimento',
    352: 'Herbert Marcondes',
    36: 'Uso Próprio',
    120: 'Carlos Benia',
    3436: 'Uso Próprio',
    3346: 'Uso Próprio',
    38: 'Renato Mimoto',
    140: 'Marketing',
    217: 'Rogerio Casado',
    254: 'Carlos Gouveia',
    3364: 'Alexandre Nascimento',
    3360: 'Tiago Maruyama',
    3400: 'Herbert Marcondes',
    394: 'Promotora',
    371: 'Maisa Ekermann',
    231: 'Uso Próprio',
    41: 'Adriana David',
    3406: 'Alexandre Nascimento',
    3362: 'Carlos Gouveia',
    43: 'Adriana David',
    360: 'Tiago Maruyama',
    378: 'Alexandre Nascimento',
    3334: 'Herbert Marcondes',
    306: 'Amanda Bêtta',
    349: 'Lauegis Miranda',
    45: 'Adriana David',
    172: 'Carlos Benia',
    350: 'Lauegis Miranda',
    3412: 'Maisa Ekermann',
    49: 'Herbert Marcondes',
    376: 'Alexandre Nascimento',
    327: 'Renato Mimoto',
    52: 'Renato Mimoto',
    3375: 'Alexandre Nascimento',
    3369: 'Alexandre Nascimento',
    89: 'Sávio Almeida',
    3349: 'Adriana David',
    53: 'Adriana David',
    54: 'Sávio Almeida',
    3374: 'Alexandre Nascimento',
    56: 'Renato Mimoto',
    315: 'Amanda Bêtta',
    3407: 'Alexandre Nascimento',
    3376: 'Alexandre Nascimento',
    3361: 'Sávio Almeida',
    57: 'Alexandre Nascimento',
    58: 'Adriana David',
    3408: 'Alexandre Nascimento',
    3405: 'Alexandre Nascimento',
    330: 'Rogerio Casado',
    3358: 'Alexandre Nascimento',
    317: 'Maisa Ekermann',
    3354: 'Alexandre Nascimento',
    3416: 'Herbert Marcondes',
    3352: 'Alexandre Nascimento',
    61: 'Herbert Marcondes',
    4: 'Renato Mimoto',
    3383: 'Merchandising',
    148: 'Rogerio Casado',
    3423: 'Sávio Almeida',
    359: 'Rogerio Casado',
    3424: 'Sávio Almeida',
    3366: 'Alexandre Nascimento',
    66: 'Sávio Almeida',
    3410: 'Sávio Almeida',
    3356: 'Saiu',
    3343: 'Lauegis Miranda',
    211: 'Maisa Ekermann',
    153: 'Adriana David',
    3348: 'Alexandre Nascimento',
    132: 'Tiago Maruyama',
    128: 'Tiago Maruyama',
    370: 'Tiago Maruyama',
    3420: 'Alexandre Nascimento',
    72: 'Tiago Maruyama',
    79: 'Tiago Maruyama',
    1: 'Tiago Maruyama',
    160: 'Carlos Benia',
    117: 'Tiago Maruyama',
    146: 'Uso Próprio',
    3395: 'Uso Próprio',
    154: 'Herbert Marcondes',
    77: 'Adriana David',
    329: 'Rogerio Casado',
    78: 'Adriana David',
    3370: 'Alexandre Nascimento',
    112: 'Tiago Maruyama',
    3414: 'Carlos Benia',
    3351: 'Maurício Rodrigues',
    3339: 'Maisa Ekermann',
    9999: 'Uso Próprio',
    9998: 'Herbert Marcondes',
    3389: 'Amanda Bêtta',
    9997: 'Merchandising',
    9996: 'Promotora',
    9995: 'Marketing',
    9994: 'Saiu',
}
